ARCHITECTURE: facebook/convnextv2-base-22k-224
LEARNING_RATE: 0.0001
DATASET: combined
# options: flowers102, imagewoof, combined
EPOCHS: 30
OPTIMIZER: 'adamw' 
BATCH_SIZE: 32
SCHEDULER: null
ROOT_DIR : 'data'
DATA_AUG: null